name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: cachix/install-nix-action@v13
        name: Install Nix
      - run: nix-build

  cabal-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.10.4"]
        cabal: ["3.6.2.0"]
        os: [ubuntu-latest, macOS-latest]
    name: build and test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal build --enable-tests && cabal test
